%YAML:1.0
CameraMat: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [1903.3, 0, 1914.0,
          0, 1904.73, 1075.27,
          0, 0, 1]

DistCoeffs: !!opencv-matrix
  rows: 5
  cols: 1
  dt: d
  data: [-0.015362, -0.047965, 0.059126, -0.02846, 0.0]

Camera.width: 3200
Camera.height: 1800

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [-0.99986331929, 0.00285909988, 0.01628398894, -0.00972339377,
         0.01630873014, 0.00885463465, 0.99982779556, -0.54317009648,
         0.00271441876, 0.99995670956, -0.00890005268, -1.95922973802,
         0.0, 0.0, 0.0, 1.0]
